//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Variables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RxGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RxGeneral() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Variables.RxGeneral", typeof(RxGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10_PAQUETE_FIBRA.
        /// </summary>
        public static string _10_PAQUETE_FIBRA {
            get {
                return ResourceManager.GetString("10_PAQUETE_FIBRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12_PARAMETROS_CTAS_NETWORKING.
        /// </summary>
        public static string _12_PARAMETROS_CTAS_NETWORKING {
            get {
                return ResourceManager.GetString("12_PARAMETROS_CTAS_NETWORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13_TABLA_SUSTITUCION.
        /// </summary>
        public static string _13_TABLA_SUSTITUCION {
            get {
                return ResourceManager.GetString("13_TABLA_SUSTITUCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 14_TEL_PRIVADOS.
        /// </summary>
        public static string _14_TEL_PRIVADOS {
            get {
                return ResourceManager.GetString("14_TEL_PRIVADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 15_TRAMITES.
        /// </summary>
        public static string _15_TRAMITES {
            get {
                return ResourceManager.GetString("15_TRAMITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 16_TRASPROMOS.
        /// </summary>
        public static string _16_TRASPROMOS {
            get {
                return ResourceManager.GetString("16_TRASPROMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 17_DISTRIBUCION_EMAIL.
        /// </summary>
        public static string _17_DISTRIBUCION_EMAIL {
            get {
                return ResourceManager.GetString("17_DISTRIBUCION_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 18_CARTAS_ANEXAS.
        /// </summary>
        public static string _18_CARTAS_ANEXAS {
            get {
                return ResourceManager.GetString("18_CARTAS_ANEXAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 19_CUPONES_PUBLICITARIOS.
        /// </summary>
        public static string _19_CUPONES_PUBLICITARIOS {
            get {
                return ResourceManager.GetString("19_CUPONES_PUBLICITARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2_SERVICIOS_ADICIONALES_TV.
        /// </summary>
        public static string _2_SERVICIOS_ADICIONALES_TV {
            get {
                return ResourceManager.GetString("2_SERVICIOS_ADICIONALES_TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20_NIVEL_RECLAMACION.
        /// </summary>
        public static string _20_NIVEL_RECLAMACION {
            get {
                return ResourceManager.GetString("20_NIVEL_RECLAMACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 21_DISTRIBUCION_DUAL.
        /// </summary>
        public static string _21_DISTRIBUCION_DUAL {
            get {
                return ResourceManager.GetString("21_DISTRIBUCION_DUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 23_FECHAS_PAGO_FIJAS.
        /// </summary>
        public static string _23_FECHAS_PAGO_FIJAS {
            get {
                return ResourceManager.GetString("23_FECHAS_PAGO_FIJAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 25_CLAUSULAS_PERMANENCIAS.
        /// </summary>
        public static string _25_CLAUSULAS_PERMANENCIAS {
            get {
                return ResourceManager.GetString("25_CLAUSULAS_PERMANENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 26_LLANOS.
        /// </summary>
        public static string _26_LLANOS {
            get {
                return ResourceManager.GetString("26_LLANOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 27_PROMOSIONES_LTE.
        /// </summary>
        public static string _27_PROMOSIONES_LTE {
            get {
                return ResourceManager.GetString("27_PROMOSIONES_LTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 29_DISTRIBUCION_SMS.
        /// </summary>
        public static string _29_DISTRIBUCION_SMS {
            get {
                return ResourceManager.GetString("29_DISTRIBUCION_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3_CUENTAS_RETENIDAS.
        /// </summary>
        public static string _3_CUENTAS_RETENIDAS {
            get {
                return ResourceManager.GetString("3_CUENTAS_RETENIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30_FACTURACION_VENCIDA_LTE_CORPORATIVO.
        /// </summary>
        public static string _30_FACTURACION_VENCIDA_LTE_CORPORATIVO {
            get {
                return ResourceManager.GetString("30_FACTURACION_VENCIDA_LTE_CORPORATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 31_PAGO_INMEDIATO.
        /// </summary>
        public static string _31_PAGO_INMEDIATO {
            get {
                return ResourceManager.GetString("31_PAGO_INMEDIATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 32_SVAS_Fuera_Bundle.
        /// </summary>
        public static string _32_SVAS_Fuera_Bundle {
            get {
                return ResourceManager.GetString("32_SVAS_Fuera_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 33_CARTAS_MORA.
        /// </summary>
        public static string _33_CARTAS_MORA {
            get {
                return ResourceManager.GetString("33_CARTAS_MORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 34_EMAIL_PRIVADO.
        /// </summary>
        public static string _34_EMAIL_PRIVADO {
            get {
                return ResourceManager.GetString("34_EMAIL_PRIVADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 35_MENSAJE_CLIENTES_SUSPENDIDOS.
        /// </summary>
        public static string _35_MENSAJE_CLIENTES_SUSPENDIDOS {
            get {
                return ResourceManager.GetString("35_MENSAJE_CLIENTES_SUSPENDIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 36_FACTURA_ELECTRONICA.
        /// </summary>
        public static string _36_FACTURA_ELECTRONICA {
            get {
                return ResourceManager.GetString("36_FACTURA_ELECTRONICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4_DISTRIBUCION_ESPECIAL.
        /// </summary>
        public static string _4_DISTRIBUCION_ESPECIAL {
            get {
                return ResourceManager.GetString("4_DISTRIBUCION_ESPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5_DOC1_PARTICIONES.
        /// </summary>
        public static string _5_DOC1_PARTICIONES {
            get {
                return ResourceManager.GetString("5_DOC1_PARTICIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 51_PROCUNI.
        /// </summary>
        public static string _51_PROCUNI {
            get {
                return ResourceManager.GetString("51_PROCUNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6_LLAVES_CODIGOS_FACTU.
        /// </summary>
        public static string _6_LLAVES_CODIGOS_FACTU {
            get {
                return ResourceManager.GetString("6_LLAVES_CODIGOS_FACTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7_LOC_BAR.
        /// </summary>
        public static string _7_LOC_BAR {
            get {
                return ResourceManager.GetString("7_LOC_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9_OFICINAS_ORDENAMIENTOS.
        /// </summary>
        public static string _9_OFICINAS_ORDENAMIENTOS {
            get {
                return ResourceManager.GetString("9_OFICINAS_ORDENAMIENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimado  Cliente: Por favor cancele oportunamente esta factura, de lo contrario se suspenderá el servicio y se cobrará un cargo de reconexión de $5,950 incluádo IVA. Efectúe el pago únicamente en efectivo o cheque de gerencia..
        /// </summary>
        public static string TextoMora_1 {
            get {
                return ResourceManager.GetString("TextoMora_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimado  Cliente: Su servicio se encuentra suspendido debido a que el sistema aún no registra su pago. Para que pueda continuar beneficiándose de nuestros servicios, le invitamos a efectuar el pago a la mayor brevedad únicamente en efectivo o cheque de gerencia. Si cancelá su factura anterior después de la fecha límite de pago y éste no fue aplicado en la presente factura, por favor acérquese a nuestro Centro de Servicios más cercano con el fin de expedirle un recibo con el valor real a pagar..
        /// </summary>
        public static string TextoMora_2 {
            get {
                return ResourceManager.GetString("TextoMora_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimado Cliente: Por favor cancele oportunamente esta factura, de lo contrario se suspenderá el servicio y se cobrará un cargo de reconexión de $5,950 incluido IVA. Efectúe el pago por ventanilla en efectivo, cheque de gerencia o a través de medios electrónicos. Evite el reporte a centrales de riesgo..
        /// </summary>
        public static string TextoMora_3 {
            get {
                return ResourceManager.GetString("TextoMora_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimado Cliente: Para continuar disfrutando de nuestros servicios, lo invitamos a efectuar el pago a la brevedad posible, por ventanilla en efectivo o cheque de gerencia y a través de medios electrónicos. Si la factura fue cancelada extemporáneamente y no se ve reflejado en esta factura, por favor visite nuestro centro de servicio más cercano para expedirle el recibo para el pago. Evite el reporte a centrales de riesgo..
        /// </summary>
        public static string TextoMora_4 {
            get {
                return ResourceManager.GetString("TextoMora_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima factura, evite el retiro definitivo de los servicios. Esta factura solo se recibe hasta la fecha límite de pago. Si no es cancelada se enviar a cobro prejudirico, incrementándose el valor en intereses y honorarios. Cancele por ventanilla, en efectivo o cheque de gerencia y por medios electrónicos. Evite el reporte a centrales de riesgo. Conforme lo dispone el decreto 2150 de 1995, la firma mecánica que aparece a continuación tiene plena validez para todos los efectos legales Saul Kattan Cohen Represe [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string TextoMora_5 {
            get {
                return ResourceManager.GetString("TextoMora_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRESENTA CHEQUE DEVUELTO. SU SERVICIO SERÁ SUSPENDIDO. SIRVASE CANCELAR ESTA FACTURA EN EFECTIVO O CHEQUE DE GERENCIA Y DOS DIAS DESPUES ACERCARSE A RECLAMAR EL CHEQUE A LA COORDINACION DE RECAUDO  Cra 8 No 20 - 00  Piso 8..
        /// </summary>
        public static string TextoTramites {
            get {
                return ResourceManager.GetString("TextoTramites", resourceCulture);
            }
        }
    }
}
